trt_grp <- data.frame(cost = rgamma(250, 1000), effect = runif(250, 1, 20), group = rep("treatment", 250))
control_grp <- data.frame(cost = rgamma(250, 10), effect = runif(250, 50, 100), group = rep("control", 250))
data <- rbind(trt_grp, control_grp)
ref <- 'control'
#'

# bootstrap the ratio of :
# Sepal.Length - Sepal.Width / Petal.Length - Petal.Width

library(boot) # package for bootstrap
ci.type = "bca"
boot_icer <- function(cost, effect, group, ref, data, R = 999, ci.type = "bca", na.omit = TRUE){
  # set the order of variables
  #var_order <- c("cost", "effect", "group")
  # data <- data[, var_order]


  func <- function(data, i) {


    data <- data[i,]
    c(
      # 1 = cost ; 2 = effect

      mean_cost <- mean(data[data$group != ref, 1]) - mean(data[data$group == ref, 1]),
      mean_effect <- mean(data[data$group != ref, 2]) - mean(data[data$group == ref, 2]),
      icer <- (mean(data[data$group != ref, 1]) - mean(data[data$group == ref, 1])) / (mean(data[data$group != ref, 2]) - mean(data[data$group == ref, 2]))
    )
  }

  set.seed(1234)
  myboot <- boot(data, func, R = 1000)

  ci_estim_cost <- round(boot.ci(boot.out = myboot, type = ci.type, index = 1)$bca[4:5],3)
  ci_estim_effect <- round(boot.ci(boot.out = myboot, type = ci.type, index = 2)$bca[4:5],3)
  ci_estim_icer <- round(boot.ci(boot.out = myboot, type = ci.type, index = 3)$bca[4:5],3)



  estim_icer <- data.frame(
    Outcome = c("Mean Delta Cost", "Mean Delta Effect", "ICER"),
    Estimated = round(colMeans(myboot$t),3),
    Observed = round(myboot$t0,3),
    Std.Error = round(apply(myboot$t, 2, sd),3),
    Bias = round((mean(myboot$t) - myboot$t0) ,3),
    CI = c(paste('[',ci_estim_cost[1],';', ci_estim_cost[2],']'),
           paste('[', ci_estim_effect[1],';', ci_estim_effect[2], ']'),
           paste('[', ci_estim_icer[1],';', ci_estim_icer[2], ']')
    )
  )

  myboot$t # R values of our statistic generated by the bootstrap procedure
  myboot$t0  # values of statistic in the original dataset
  myboot # print results of boot object

  # biais = mean(myboot$t) - myboot$t0
  # std.error = standard error of bootstrap estimate (i.e. standard deviation of bootstrap realizations)

  # Different types of bootstrap CIs : norm, basic, stud, perc, bca see ?boot and type argument

  # if( plot = TRUE )
  # plot(myboot, index = 3)
  estim_icer<- round_df(estim_icer, 3)
  tangram::tangram(estim_icer, id="tbl2", caption="Ordinary nonparametric bootstrap estmation of cost-effectiveness outcomes", style="nejm",  as.character=TRUE)



}



boot_icer(cost, effect, group, ref, data = data)

