#' Observed Cost-Effectiveness Outcomes
#'
#' This function calculates and returns observed cost-effectiveness outcomes
#' based on input data for cost, effect, and group assignments. It includes
#' observed mean and standard deviation for cost and effect, observed
#' Incremental Cost-Effectiveness Ratio (ICER), and statistical comparisons
#' between treatment and control groups.
#'
#' @param data A data frame containing the cost, effect, and group data.
#' @param cost The name of the column in `data` representing the cost.
#' @param effect The name of the column in `data` representing the effect.
#' @param group The name of the column in `data` that differentiates between treatment and control groups.
#' @param ref The reference (control) group name as a string.
#' @param na.omit Logical indicating whether NA values should be omitted. Defaults to TRUE.
#'
#' @return Returns a formatted table (as generated by the `tangram` package)
#' of the observed cost-effectiveness outcomes, including mean cost, mean effect,
#' their standard deviations, differences (Delta), confidence intervals, and p-values
#' for comparisons between treatment and control groups. Also includes a footnote
#' with the observed ICER value.
#'
#' @examples
#' trt_grp <- data.frame(group = rep("treatment", 250), cost = rgamma(250, 1000), effect = runif(250, 1, 20))
#' control_grp <- data.frame(cost = rgamma(250, 10), effect = runif(250, 50, 100), group = rep("control", 250))
#' dce <- rbind(trt_grp, control_grp)
#' ref <- "control"
#' cea(dce, "effect", "cost", "group", ref = ref)
#'
#' @export
cea <- function(data, cost, effect, group, ref, na.omit = TRUE) {

  # TO DO later :
  # must do an action on na : like omit.na !
  # warning : must have only two levels !
  # warning if groups have the same length !

  # split data by group
  group_ctrl <- subset(data, group == ref)
  group_trt <- subset(data, group != ref)

  # cost & effect observed mean and sd
  observ_c_mean <- round(c(mean(group_ctrl$cost), mean(group_trt$cost)), 4) # c(mean(data[data$group == ref, ]$cost), mean(data[data$group != ref, ]$cost)
  observ_e_mean <- round(c(mean(group_ctrl$effect), mean(group_trt$effect)), 4)
  observ_c_sd <- round(c(sd(group_ctrl$cost), sd(group_trt$cost)), 4)
  observ_e_sd <- round(c(sd(group_ctrl$effect), sd(group_trt$effect)), 4)

  # observed ICER
  observ_delta_c <- observ_c_mean[2] - observ_c_mean[1]
  observ_delta_e <- observ_e_mean[2] - observ_e_mean[1]
  observ_icer <- round((observ_delta_c / observ_delta_e), 3)

  # compare the difference in means : t test
  compar_c <- t.test(group_trt$cost, group_ctrl$cost)
  compar_e <- t.test(group_trt$effect, group_ctrl$effect)

  # percentile 95% ci and p-value
  ci <- round(c(compar_c$conf.int, compar_e$conf.int, use.names = FALSE), 3)

  # observed cea outcomes
  options(scipen = 4)
  observ_cea <- data.frame(
    Outcome = c("Mean Cost", "Mean Effect"),
    Control = c(paste0(observ_c_mean[1], " (sd ", observ_c_sd[1], ")"), paste0(observ_e_mean[1], " (sd ", observ_e_sd[1], ")")), # add (sd)
    Treatment = c(paste0(observ_c_mean[2], " (sd ", observ_c_sd[2], ")"), paste0(observ_e_mean[2], " (sd ", observ_e_sd[2], ")")), # ad (sd)
    Delta = round(c(observ_delta_c, observ_delta_e), 4),
    "percentile CI" = c(paste("[", ci[1], ";", ci[2], "]"), paste("[", ci[3], ";", ci[4], "]")),
    p.value = round(c(compar_c$p.value, compar_e$p.value), 4)
  )

  # Unnecessary to set a class ?
  # class(observ_cea) <- "observ_cea"

  observ_cea <- round_df(observ_cea, 3)
  tangram::tangram(observ_cea, id = "tbl2", caption = "Observed cost-effectiveness outcomes", style = "nejm", as.character = TRUE, footnote = paste0("Observed ICER = ", observ_icer), digits = 1)
}
