#' One-Way Deterministic Sensitivity Plot
#'
#' Creates a one-way sensitivity plot from a data frame generated by
#' [dsa_icer()].
#'
#' @param df A data frame from [dsa_icer()].
#' @param metric Character string. Either `"ICER"` or `"INMB"`.
#'
#' @return A `ggplot` object.
#' @export
#'
#' @examples
#' df <- simulate_ce_trial(n = 100, seed = 123)
#' dsa <- dsa_icer(cost + effect ~ group, data = df, param = "effect",
#'                 range = seq(0.74, 0.82, 0.02), ref = "control")
#' plot_dsa(dsa, metric = "ICER")
plot_dsa <- function(df, metric = "ICER") {
  metric <- toupper(metric)
  if (metric == "NMB") metric <- "INMB"
  if (!(metric %in% names(df))) stop(paste("Column", metric, "not found."))

  plot_data <- data.frame(Parameter = df$Parameter, Value = df[[metric]])

  ggplot2::ggplot(plot_data, ggplot2::aes(x = Parameter, y = Value)) +
    ggplot2::geom_line(color = "darkred", linewidth = 1) +
    ggplot2::geom_point(color = "darkred") +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = paste("One-Way Sensitivity Analysis -", metric),
      x = "Parameter value",
      y = metric
    )
}

#' Deprecated Tornado Plot Alias
#'
#' `plot_tornado()` is kept for backward compatibility. Use `plot_dsa()`
#' instead. The plot produced by CEACT is a one-way deterministic sensitivity
#' curve, not a conventional tornado plot.
#'
#' @inheritParams plot_dsa
#'
#' @return A `ggplot` object.
#' @export
plot_tornado <- function(df, metric = "ICER") {
  .Deprecated("plot_dsa")
  plot_dsa(df, metric = metric)
}

utils::globalVariables(c("Parameter", "Value"))
